{{- if .Values.config.git.username }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "spring-cloud-config-server.fullname" . }}-git-creds
  labels:
{{ include "spring-cloud-config-server.labels" . | indent 4 }}
data:
  username: {{ .Values.config.git.username | b64enc | quote }}
  {{- if .Values.config.git.password }}
  password: {{ .Values.config.git.password | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.config.git.ssh.privateKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "spring-cloud-config-server.fullname" . }}-git-ssh-auth
  labels:
{{ include "spring-cloud-config-server.labels" . | indent 4 }}
data:
  id_rsa: {{ .Values.config.git.ssh.privateKey }}
  known_hosts: {{ .Values.config.git.ssh.knownHosts }}
{{- end }}
---
