# This is a basic workflow to help you get started with Actions

name: Refresh Helm Index From Releases

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  refresh-index:
    runs-on: ubuntu-latest
    container:
      image: "quay.io/helmpack/chart-releaser:v1.3.0"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Init
        run: | 
          env
          ls -la
          cr --help
